<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/stylePost.css">
    <title>Turno Reservado</title>
</head>
<body>
    <div class="container">
        <h1>Tu turno fue cancelado con exito!</h1>
        <p>Vuelve a realizar un reserva</p>
        <div class="button-group">
            <a href="/index.php?action=reservar" class="btn primary">Volver al Inicio</a>
        </div>
    </div>
</body>
</html>
